plugin:
    name: 'sgdinstitute.directory::lang.plugin.name'
    description: 'sgdinstitute.directory::lang.plugin.description'
    author: 'SGD Institute'
    icon: oc-icon-users
    homepage: ''
navigation:
    directory:
        label: 'sgdinstitute.directory::lang.plugin.name'
        url: sgdinstitute/directory/human
        icon: icon-users
        sideMenu:
            add-human:
                label: 'Add New Human'
                url: sgdinstitute/directory/human/create
                icon: icon-plus
            human:
                label: 'sgdinstitute.directory::lang.directory.humans'
                url: sgdinstitute/directory/human
                icon: icon-user-secret
            groups:
                label: 'sgdinstitute.directory::lang.directory.groups'
                url: sgdinstitute/directory/group
                icon: icon-sitemap
