list: $/sgdinstitute/directory/models/group/columns.yaml
modelClass: SGDInstitute\Directory\Models\Group
title: Group
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sgdinstitute/directory/group/update/:id'
